# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examRetake_python', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('travelDateFrom', models.DateField()),
                ('travelDateTo', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripsByThisUser', to='examRetake_python.User')),
                ('joined_by', models.ManyToManyField(related_name='joinedTripsByThisUser', to='examRetake_python.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='liked_by',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
