# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examRetake_python', '0002_auto_20180821_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='travelDateFrom',
            new_name='arrivalDate',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='travelDateTo',
            new_name='departureDate',
        ),
    ]
