# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examRetake_python', '0003_auto_20180821_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripsForThisUser', to='examRetake_python.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='joined_by',
            field=models.ManyToManyField(related_name='usersJoiningThisTrip', to='examRetake_python.User'),
        ),
    ]
